### ISSUE TITLE
Port happn v2 fixes in the client to happn-3

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happn-3#193]
The client in happn v2 has changed to discard events if all listeners have been removed. This means the client doesn't try to subscribe when connecting again, which saves unnecessary transactions.

**Comment by southbite** [comment]
Hi Johan, question: 
Would this be what is necessary:
https://github.com/happner/happn-3/blob/master/lib/client.js#L1564
In which case, we are clearing out the events object if there are no more listeners. This has been tested as well.
