### ISSUE TITLE
Client socket memory leak.

### ISSUE THREAD

**Issue by ErasmusJW** [happner/happn-3#252]
When a client primus socket encounter an error calling `end()` on the socket does not fully remove all handles.
https://github.com/happner/happn-3/blob/bea101549faf052e57c853527dab8c4df1405f1c/lib/client.js#L411-L415

This might be a bug with primus or one of it dependencies.

A fix could be to call destroy on socket
`
        socket
          .once('close', function() {
            setTimeout(() => {
              socket.destroy();
              callback(e.error || e);
            }, 0);
          })
          .end();
`

**Comment by ErasmusJW** [comment]
Added a test that show the memory leak
https://github.com/ErasmusJW/happn-3/blob/issue-252/test/integration/client/socket-error-mem-leak.js
Along with an updated client that prevent it by callig destroy
https://github.com/ErasmusJW/happn-3/blob/issue-252/lib/client.js

**Comment by southbite** [comment]
fixed in happn-3@11.1.3
