### ISSUE TITLE
strict bucket unsubscribe tests all failing

### ISSUE THREAD

**Issue by nomilous** [happner/happn-3#49]
https://github.com/happner/happn-3/blob/issues/48/test/c9_unsubscribe_changes_eventemitter.js#L110

**Comment by nomilous** [comment]
skipping them all

**Comment by southbite** [comment]
created new branch, https://github.com/happner/happn-3/tree/issue/49

**Comment by southbite** [comment]
fixed, although I needed to ignore 2 of the tests as they relied on the non-strict buckets internals:

"should remove only the correct subscriptionData entry without wildcard"
"should remove only the correct subscriptionData entry with wildcard"
