### ISSUE TITLE
Implement heartbeat skip capability that was released in happn/happn#158 in happn-3

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happn-3#67]
needed because of server-side changes required to support heartbeat. happn clients already support this

04/01/19-JCE: Closed via https://github.com/happner/happn-3/pull/190/

01/29/19-ENG: Added to [TR4127 (SB) - Happner-2 issues](https://github.com/orgs/FieldServer/projects/218)

01/28/19-ENG: High priority for SB, would like to get into happner-2 core app upgrade

**Comment by nomilous** [comment]
Have we cleared it with the c client implementors that the changed server-side ping/pong behaviour will not break their client?

https://github.com/happner/happn/issues/158#issuecomment-307118839
